title: Fork Systems
email: ross@forksystems.net
baseurl: "/"
url: "https://forksystems.net"
twitter: forkwhilefork_
phone: "+442920180265"

permalink: /:categories/:year/:month/:day/:basename/

plugins:
  - jekyll-seo-tag

include:
  - assets

collections:
  services:
    output: true
