title: Fork Systems
email: your-email@example.com
baseurl: "/"
url: "https://forksystems.net"
twitter: jekyllrb
phone: "+442920180265"

permalink: /:categories/:year/:month/:day/:basename/

plugins:
  - jekyll-seo-tag

include:
  - assets

collections:
  services:
    output: true
