title: Fork Systems
email: your-email@example.com
baseurl: "/fork-systems-website"
url: "https://45.129.95.4:4000"
twitter: jekyllrb
phone: "+442920180265"

permalink: /:categories/:year/:month/:day/:basename/

plugins:
  - jekyll-seo-tag

include:
  - assets

collections:
  services:
    output: true